---
name: integration-test
releases:
- name: openvpn
  url: file://((repo_dir))
  version: create
update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
instance_groups:
- name: role1
  azs: [z1]
  jobs:
  - name: openvpn
    release: openvpn
    provides:
      openvpn:
        as: role1
    properties:
      <<: *openvpn
      server: 192.168.202.0 255.255.255.0
      tls_crypt: |
        -----BEGIN OpenVPN Static key V1-----
        9ebb98f7d6cff536b91b506d19fb4e44
        1eef3f2c25ef8351e1472131a2ff92c0
        208db738549d1fd5c97f77b4b71f8836
        16450c1f1dfddf201be62227c53cbad3
        a2c41f27461b52c0f0b10c2f15bdd783
        32db63a4f1a41e307c3d319656d7ce69
        870cc609852d5b7f742258cd2dc7c171
        cfe8d0c54255989104ebbd40a843b945
        75fc6e66cad1decb253180699b25c009
        960ed59a6963ee8b72a5a491afb800a1
        fe312a3a8478b20c0803845d6ead40d0
        ea59da0b2c2ae90f2cda3c782a4804df
        2d71fd569149180474b5c57d72874637
        8a51e54443fe31106d609a472a1ba8b0
        0134fbdb0e216f7f3178fe800e4d65c3
        888c777f538bee96595cd28630f354e5
        -----END OpenVPN Static key V1-----
  - name: openvpn-client
    release: openvpn
    consumes:
      openvpn:
        from: role2
    properties:
      certificate: ((role1_client.certificate))
      private_key: ((role1_client.private_key))
  instances: 1
  stemcell: default
  vm_type: default
  networks:
  - name: default
- name: role2
  azs: [z1]
  jobs:
  - name: openvpn
    release: openvpn
    provides:
      openvpn:
        as: role2
    properties:
      <<: *openvpn
      server: 192.168.206.0 255.255.255.0
      tls_crypt: |
        -----BEGIN OpenVPN Static key V1-----
        24a8774a0d317449775237ee2b305c8c
        945d05724c1b1127363957c30eab299a
        3d702cb28424ae5c4cb28faad05c1613
        2d45f2a896b3c22a0c3cb6bf46ced6bf
        0d2d068fe2313644d2dc4ff51a895911
        996fa2a1c64cb4dc9b3f32c3b6f57d50
        bed149242a201a72df639e300861485d
        388ca77ce55d9d78d711db3597de61b3
        76bcf0e84228cde9ef2ac5ab055731f5
        d900490f3a9a3bd72cf0f3c3aefd74c1
        31eaf11dd9ca5019b410c343882f7597
        9a7b3736ac721967a563e78e56dff19d
        a0500be1dc7c77591781001554082f28
        5f4fdea282f17202943ed80edd84cd8a
        c15b0a7fa1458acaa9ee30ca5c9e81f1
        6055d1f8e19c90fa7486667366dadf67
        -----END OpenVPN Static key V1-----
  - name: openvpn-client
    release: openvpn
    consumes:
      openvpn:
        from: role1
    properties:
      certificate: ((role2_client.certificate))
      private_key: ((role2_client.private_key))
  instances: 1
  stemcell: default
  vm_type: default
  networks:
  - name: default
properties:
  openvpn: &openvpn
    ca_crt: ((server_crt.ca))
    server_crt: ((server_crt.certificate))
    server_key: ((server_crt.private_key))
    dh_pem: |
      -----BEGIN DH PARAMETERS-----
      MIIBCAKCAQEA/oih/YXvkf13npOIF5LW170/V5j4R20NjL/IzgdZUYMlsQtm5zMZ
      LwA8Vk1v9UnSWkopAGuJ8gZxz4qKk2p2MLzHSDwXC5khGrrJlHfjn7H0lYilyFqn
      2YhmfCQ7z7ih0jUS/iNf/+xUmfoJn/2OMEY3gmcAxAbtVRqNtGFwsTjtap3Rgbt9
      /j7Xbrsp3JqSeWN3VSqMzAgUrjkkkv52HcDo4zA1KfN7m+ROj/uGxcrmvZr7G0RK
      9yJ2f8I1x8EW3p+CmWhHcmoNyxxlfRHIsZ+82+BIessN99pSxCbjWvhggntFLRwC
      fcrq5wk9ei7dzYjZHSPHqvhmmZgWKJZYQwIBAg==
      -----END DH PARAMETERS-----
variables:
- name: ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: server_crt
  type: certificate
  options:
    ca: ca
    common_name: server
    alternative_names:
    - "*.role1.default.openvpn-deployment.bosh"
    - "*.role2.default.openvpn-deployment.bosh"
    extended_key_usage:
    - server_auth
- name: role1_client
  type: certificate
  options:
    ca: ca
    common_name: role1
    extended_key_usage:
    - client_auth
- name: role2_client
  type: certificate
  options:
    ca: ca
    common_name: role2
    extended_key_usage:
    - client_auth
